version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: flowdesk-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: flowdesk
    ports:
      - "3306:3306"